server:
  port: 8090
  servlet:
    context-path: /api/gymail

security:
  jwt:
    secret: "gymail-lp3-jwt"
    expiration: 86400000
  public:
    path: "/public/**"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-235-167-210.compute-1.amazonaws.com:5432/d6cious8elomkr?createDatabaseIfNotExist=true
    username: ctxeiyzfsuvinh
    password: ${DATABASE_URL}
    

---

spring:
  profiles: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gymail?createDatabaseIfNotExist=true
    username: root
    password: rootroot
