server:
  port: 8090
  servlet:
    context-path: /api/gymail

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/gymail
    username: root
    password: #pass

security:
  jwt:
    secret: "gymail-lp3-jwt"
    expiration: 86400000 # 1 dia em milisegundos
  public:
    path: "/public/**"